### PR TITLE
Setup infra

### PR DESCRIPTION
**Pull request by z1yoon**
https://www.notion.so/Step-by-Step-Guide-to-Encrypting-and-Decrypting-NSHM-env-Files-11f5aac8434380f6bb77def035afdbac?showMoveTo=true&saveParent=true

I would like to control our envs like this, please fix me if there's wrong or better way~!

### CODE REVIEW

**Comment by mrcaidev** [comment]
Why is this PR so big 😰😰😰 I looked into the files changed, and it looks like this PR kinda overlaps with the work in #32. I don't know what will happen... This should not be the case

**Comment by mrcaidev** [comment]
In step 2, we need to manually enter the `.env` we have changed. This sounds troublesome, not elegant, and not automated enough.

## Alternative 1

Just encrypt all `.env` files altogether. Encryption time won't be very long I guess.

## Alternative 2

Use `git diff --name-only` to find out which `.env` file has been changed in the working tree. And only encrypt that `.env` again.

**Comment by mrcaidev** [comment]
In step 3, we don't need a dedicated `envs` folder to host all `*.env.gpg` files. We can safely store them side by side with `.env`, right inside `services/*`.

```
services/
  account/
    .env
    .env.gpg
  item/
    .env
    .env.gpg
  ...
```

**Comment by mrcaidev** [comment]
The rest is pretty nice and smooth. 👍

**Comment by z1yoon** [comment]
@mrcaidev 
as .env is ignored I will encrypt all files then! 
and I was adding gpg file inside respective service dir but I realized gpg files inside one folder including infra related will be easier to manage it. Even though I can decrypt gpg files from respective service dir still I need to keep envs dir to decrypt any other gpg files not related to services.  I would like to manage all gpg files in one dir. So .env will be developer responsibility , gpg is devops responsibility to manage it.

**Comment by mrcaidev** [comment]
> I would like to manage all gpg files in one dir. So .env will be developer responsibility , gpg is devops responsibility to manage it.

That's fair. 👍 I will go with that.

**Pull request merged**
